#!/bin/bash
#
# SwizGuard add-client
# Generates a single Xray client config with chained WireGuard + VLESS+REALITY.
# No separate WireGuard daemon needed on the client — Xray handles everything
# in userspace via gVisor.
#
# Usage: sudo bash add-client.sh <client-name>
# Example: sudo bash add-client.sh macbook

set -euo pipefail

R='\033[91m' G='\033[92m' Y='\033[93m' C='\033[96m' B='\033[1m' X='\033[0m'
info()  { echo -e "  ${C}[*]${X} $1"; }
ok()    { echo -e "  ${G}[+]${X} $1"; }
warn()  { echo -e "  ${Y}[!]${X} $1"; }
fail()  { echo -e "  ${R}[✗]${X} $1"; exit 1; }

[ "$EUID" -ne 0 ] && fail "Run as root"
[ $# -lt 1 ] && fail "Usage: $0 <client-name>"

CLIENT_NAME="$1"
SWIZ_DIR="/etc/swizguard"
WG_CONF="/etc/wireguard/wg1.conf"
CRED_FILE="$SWIZ_DIR/credentials.env"
CLIENT_DIR="$SWIZ_DIR/clients/$CLIENT_NAME"

[ ! -f "$CRED_FILE" ] && fail "Server not set up — run setup-server.sh first"
[ -d "$CLIENT_DIR" ] && fail "Client '$CLIENT_NAME' already exists"

# shellcheck source=/dev/null
source "$CRED_FILE"

# Older installs predate WG_SUBNET6 in credentials.env.
WG_SUBNET6="${WG_SUBNET6:-fd07::7}"

echo -e "${C}${B}"
echo "╔══════════════════════════════════════════════════════╗"
echo "║          SwizGuard — add client: $CLIENT_NAME"
echo "╚══════════════════════════════════════════════════════╝"
echo -e "${X}"

# ─── Assign client IP ────────────────────────────────────────────
# Find the highest IPv4 octet currently in use and increment, so removing
# a peer doesn't cause the next add to collide with an existing one.

# `|| true` matters: on a fresh server no peer exists yet, grep exits 1, and
# under `set -o pipefail` that would abort the very first `swizguard add`.
HIGHEST=$(grep -oE "${WG_SUBNET//./\\.}\.[0-9]+/32" "$WG_CONF" 2>/dev/null \
    | awk -F'[./]' '{print $4}' | sort -n | tail -1 || true)
HIGHEST=${HIGHEST:-1}  # .1 is the server itself
CLIENT_NUM=$((HIGHEST + 1))
if [ "$CLIENT_NUM" -lt 2 ]; then CLIENT_NUM=2; fi
[ "$CLIENT_NUM" -gt 254 ] && fail "Subnet ${WG_SUBNET}.0/24 is full (254 clients)"

CLIENT_IPV4="${WG_SUBNET}.${CLIENT_NUM}"
CLIENT_IPV6="${WG_SUBNET6}${CLIENT_NUM}"

info "Client tunnel IP: $CLIENT_IPV4 / $CLIENT_IPV6"

# ─── Generate WireGuard client keys ──────────────────────────────

mkdir -p "$CLIENT_DIR"

wg genkey | tee "$CLIENT_DIR/private.key" | wg pubkey > "$CLIENT_DIR/public.key"
chmod 600 "$CLIENT_DIR/private.key"

CLIENT_WG_PRIVKEY=$(cat "$CLIENT_DIR/private.key")
CLIENT_WG_PUBKEY=$(cat "$CLIENT_DIR/public.key")

ok "Client WireGuard keys generated"

# ─── Add peer to server WireGuard ────────────────────────────────

cat >> "$WG_CONF" <<PEEREOF

[Peer]
# $CLIENT_NAME
PublicKey = $CLIENT_WG_PUBKEY
AllowedIPs = ${CLIENT_IPV4}/32, ${CLIENT_IPV6}/128
PEEREOF

wg set wg1 peer "$CLIENT_WG_PUBKEY" allowed-ips "${CLIENT_IPV4}/32,${CLIENT_IPV6}/128"
ok "Peer added to WireGuard server"

# ─── Generate Xray + sing-box client configs (via shared template) ─
# Architecture:
#   Desktop (Xray):  SOCKS/HTTP inbound → WireGuard outbound → dialerProxy → VLESS+REALITY+Vision
#   Mobile (sing-box): TUN inbound → WireGuard endpoint → detour → VLESS+REALITY+Vision
#   Server:          VLESS+REALITY+Vision inbound → freedom outbound → 127.0.0.1:$WG_PORT (local WG)

SCRIPT_BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
CLIENT_NAME="$CLIENT_NAME" \
CLIENT_IPV4="$CLIENT_IPV4" \
CLIENT_IPV6="$CLIENT_IPV6" \
CLIENT_WG_PRIVKEY="$CLIENT_WG_PRIVKEY" \
CLIENT_WG_PUBKEY="$CLIENT_WG_PUBKEY" \
CLIENT_DIR="$CLIENT_DIR" \
SERVER_IP="$SERVER_IP" \
XRAY_PORT="$XRAY_PORT" \
WG_PORT="$WG_PORT" \
CLIENT_UUID="$CLIENT_UUID" \
CAMOUFLAGE_DEST="$CAMOUFLAGE_DEST" \
REALITY_PUBLIC_KEY="$REALITY_PUBLIC_KEY" \
SERVER_WG_PUBLIC_KEY="$SERVER_WG_PUBLIC_KEY" \
SHORT_ID="$SHORT_ID" \
bash "$SCRIPT_BASE_DIR/regen-client-configs.sh"

ok "Xray client config generated (xray-client.json)"
ok "sing-box client config generated (singbox-client.json)"

# (xray-client.json and singbox-client.json are generated by the
#  regen-client-configs.sh call above — see that file for templates)

# ─── Generate launcher script (no sudo needed — Xray is userspace) ─

CLIENT_NAME="$CLIENT_NAME" \
CLIENT_DIR="$CLIENT_DIR" \
bash "$SCRIPT_BASE_DIR/_generate-launcher.sh"
ok "Client launcher script generated"

# ─── Summary ─────────────────────────────────────────────────────

echo ""
echo -e "${G}${B}╔══════════════════════════════════════════════════════╗"
echo "║           CLIENT '$CLIENT_NAME' CREATED                "
echo -e "╚══════════════════════════════════════════════════════╝${X}"
echo ""
echo -e "  ${B}Files:${X}"
echo "    xray-client.json       — Xray config for desktop (macOS/Linux/Windows)"
echo "    singbox-client.json    — sing-box config for iOS SFI / Android SFA"
echo "    connect-${CLIENT_NAME}.sh   — launcher script for desktop"
echo ""
echo -e "  ${B}How it works:${X}"
echo "    Single process on the client. No wg-quick. No sudo needed."
echo "    Apps → local proxy/TUN → WireGuard outbound (userspace)"
echo "           → chained through VLESS+REALITY+Vision"
echo "           → VPS sees HTTPS to ${CAMOUFLAGE_DEST}"
echo ""
echo -e "  ${B}Desktop usage (macOS/Linux/Windows):${X}"
echo "    1. Install xray-core  (brew install xray)"
echo "    2. scp -r USER@${SERVER_IP}:${CLIENT_DIR} ./"
echo "    3. cd $CLIENT_NAME && bash connect-${CLIENT_NAME}.sh"
echo "    4. bash connect-${CLIENT_NAME}.sh enable-system-proxy   (optional)"
echo ""
echo -e "  ${B}iPhone usage (full chain via SFI):${X}"
echo "    1. Install SFI (Sing-Box For iOS) — App Store or TestFlight"
echo "    2. AirDrop singbox-client.json to iPhone, save to Files"
echo "    3. Open SFI → Profiles → + → Local → pick the JSON"
echo "    4. Dashboard → select profile → Start → Allow VPN"
echo ""
echo -e "  ${B}Android usage:${X}"
echo "    Install SFA (Sing-Box For Android), import singbox-client.json"
echo "    OR: v2rayNG custom config, import xray-client.json"
echo ""
